kind: pipeline
name: default

steps:
- name: publish
  image: banzaicloud/drone-kaniko
  settings:    
    repo: registry.example.com/example-project
    tags: ${DRONE_COMMIT_SHA}
    username: sdsd
    password: fdsfdf
    cache: true
    build_args:
    - COMMIT_SHA=${DRONE_COMMIT_SHA}
    - COMMIT_AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}
